# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
            - name: Deploy GitHub Runner to AWS (EC2)
  # Вы можете зафиксировать точный коммит или версию.
  # uses: bitovi/github-actions-deploy-github-runner-to-ec2@6e35bdc2c305bec7608655b84227b88ac75c5961
  используется: bitovi/github-actions-deploy-github-runner-to-ec2@v0
  с:
    # Указывает, следует ли выполнять это действие для извлечения кода
    checkout: # необязательный параметр, по умолчанию true
    # Будет запущена только фаза генерации BitOps, на которой компилируется код Terraform и Ansible.
    bitops_code_only: # необязательно
    # Сохраняйте код BitOps в виде артефакта GitHub
    bitops_code_store: # необязательный
    # URL репозитория для прослушивания участником забега
    repo_url:
    # Токен доступа к репозиторию
    repo_access_token:
    # Идентификатор ключа доступа к WS
    aws_access_key_id: # необязательный
    # Секретный ключ доступа AWS
    aws_secret_access_key: # необязательный
    # Токен сессии AWS
    aws_session_token: # необязательный
    # Регион AWS по умолчанию
    aws_default_region: # необязательный параметр, по умолчанию us-east-1
    # Установите этот параметр, чтобы переопределить идентификатор ресурса AWS для развертывания. По умолчанию используется `${org}-{repo}-{branch}`. Используйте с параметром destroy для удаления определенных ресурсов.
    aws_resource_identifier: # необязательный
    # JSON-объект с дополнительными тегами, которые будут включены в создаваемые ресурсы. Пример: `{"key1": "value1", "key2": "value2"}`
    aws_additional_tags: # необязательно
    # Установите значение "true", чтобы удалить стек с помощью Terraform.
    tf_stack_destroy: # необязательно
    # Измените это значение на любое, какое захотите. Будьте внимательны к последовательности. Отсутствие файла может привести к его пересозданию или пропуску уничтожения неопределенных объектов.
    tf_state_file_name: # необязательно
    # Добавить строку в файл tf-state. Установка значения `unique` приведет к созданию `tf-state-aws-unique`. Может сосуществовать с переменной tf_state_file_name.
    tf_state_file_name_append: # необязательно
    # Корзина AWS S3 для хранения состояния Terraform. По умолчанию используется `${org}-${repo}-{branch}-tf-state`
    tf_state_bucket: # необязательно
    # Принудительная очистка и удаление S3-корзины. Все содержащиеся в ней файлы будут уничтожены. Параметр `tf_stack_destroy` также должен быть `true`.
    tf_state_bucket_destroy: # необязательно
    # Имя секрета для извлечения переменных окружения из AWS Secret Manager. Может представлять собой список, разделенный запятыми, считывается по порядку. Ожидаемое содержимое в формате JSON.
    env_aws_secret: # необязательный
    # Файл, содержащий переменные среды, которые будут использоваться с приложением
    env_repo: # необязательно
    # Файл `.env`, который будет использоваться с приложением из секретов Github
    env_ghs: # необязательно
    # Файл `.env`, используемый с приложением, из переменных Github
    env_ghv: # необязательно
    # Определяет, следует ли создавать экземпляр EC2
    aws_ec2_instance_create: # необязательно
    # Строка фильтра AWS AMI. Будет использоваться для поиска последних образов на основе этой строки. По умолчанию используется `ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*`.
    aws_ec2_ami_filter: # необязательный
    # Владелец образа AWS AMI. Это гарантирует, что поставщик соответствует нашим требованиям. По умолчанию используется `099720109477`, Canonical (Ubuntu).
    aws_ec2_ami_owner: # необязательно
    # Идентификатор AWS AMI. По умолчанию будет использоваться поиск последнего образа, указанного в строке `aws_ec2_ami_filter`. Это переопределит поиск по `aws_ec2_ami_filter`.
    aws_ec2_ami_id: # необязательный
    # Установите значение true, если хотите пересоздать экземпляр EC2 при наличии более новой версии AMI.
    aws_ec2_ami_update: # необязательно
    # Профиль экземпляра AWS IAM, используемый для экземпляра EC2
    aws_ec2_iam_instance_profile: # необязательный
    # Тип экземпляра AWS
    aws_ec2_instance_type: # необязательный
    # Задайте размер тома (в ГиБ) для корневого тома на экземпляре AWS.
    aws_ec2_instance_root_vol_size: # необязательно
    # Установите значение true, чтобы избежать удаления корневого тома при завершении работы. По умолчанию — false.
    aws_ec2_instance_root_vol_preserve: # необязательно
    # Название группы безопасности EC2
    aws_ec2_security_group_name: # необязательно
    # Создает и управляет записью менеджера секретов, содержащей открытый и закрытый ключи, созданные для экземпляра EC2.
    aws_ec2_create_keypair_sm: # необязательно
    # Добавить или не добавлять публичный IP-адрес к экземпляру. (Не эластичный IP-адрес)
    aws_ec2_instance_public_ip: # необязательный
    # Список портов, которые будут включены в качестве правила входящего трафика в группе безопасности EC2, в формате [xx,yy] - не ELB
    aws_ec2_port_list: # необязательно
    # Относительный путь в репозитории для скрипта, предоставленного пользователем, который будет выполнен при создании экземпляра EC2 с помощью Terraform.
    aws_ec2_user_data_file: # необязательный параметр, по умолчанию файл не предоставлен
    # Если файл user_data изменится, экземпляр остановится и запустится заново. Следовательно, публичный IP-адрес изменится. По умолчанию — true.
    aws_ec2_user_data_replace_on_change: # необязательно
    # JSON-объект с дополнительными тегами, которые будут включены в создаваемые ресурсы. Пример: `{"key1": "value1", "key2": "value2"}`
    aws_ec2_additional_tags: # необязательный
    # Определите, следует ли создавать VPC
    aws_vpc_create: # необязательно
    # Задайте конкретное имя для VPC
    aws_vpc_name: # необязательно
    # Определяем базовый блок CIDR, который делится на блоки CIDR подсети. По умолчанию используется 10.0.0.0/16.
    aws_vpc_cidr_block: # необязательный
    # Разделенный запятыми список общедоступных подсетей. По умолчанию используется 10.10.110.0/24
    aws_vpc_public_subnets: # необязательно
    # Разделенный запятыми список частных подсетей. Если подсетей нет, они не будут созданы.
    aws_vpc_private_subnets: # необязательно
    # Разделенный запятыми список зон доступности. По умолчанию используется `aws_default_region.
    aws_vpc_availability_zones: # необязательно
    # Идентификатор AWS VPC. Принимает значения `vpc-###`.
    aws_vpc_id: # необязательный
    # Укажите подсеть, которая будет использоваться с экземпляром. Если подсеть не указана, будет выбрана другая.
    aws_vpc_subnet_id: # необязательный
    # Включает NAT-шлюз
    aws_vpc_enable_nat_gateway: # необязательно
    # Создает только один NAT-шлюз
    aws_vpc_single_nat_gateway: # необязательно
    # Разделённый запятыми список идентификаторов IP-адресов для повторного использования в NAT-шлюзах
    aws_vpc_external_nat_ip_ids: # необязательно
    # JSON-объект с дополнительными тегами, которые будут включены в создаваемые ресурсы. Пример: `{"key1": "value1", "key2": "value2"}`
    aws_vpc_additional_tags: # необязательный
    #
    aws_secret_env: # необязательно
    #
    repo_env: # необязательно
    #
    dot_env: # необязательно
    #
    ghv_env: # необязательный
    #
    stack_destroy: # необязательно
    #
    дополнительные теги: # необязательно
    #
    ec2_instance_profile: # необязательный
    #
    ec2_instance_type: # необязательный
    #
    ec2_ami_id: # необязательный
    #
    ec2_ami_update: # необязательно
    #
    ec2_volume_size: # необязательный параметр
    #
    ec2_root_preserve: # необязательно
    #
    ec2_security_group_name: # необязательно
    #
    ec2_create_keypair_sm: # необязательно
    #
    ec2_instance_public_ip: # необязательный
    #
    ec2_user_data_file: # необязательный параметр, по умолчанию файл не предоставлен
    #
    ec2_user_data_replace_on_change: # необязательно
    #
    ec2_additional_tags: # необязательный
          
